services:
  # frontend:
  #   build:
  #     context: ./frontend/
  #     dockerfile: ./frontend/Dockerfile
  #   depends_on:
  #     - api
  #     - postgres
  #   ports:
    
  api:
    build:
      context: ./unkex/
      dockerfile: ./unkex/docker/Docker.api
    depends_on:
      - postgres 
    ports:
      - "8000:5000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: unkex 
      DB_PASSWORD: kex123
      DB_NAME: unkex
  postgres:
    image: postgres:14-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=kex123
      - POSTGRES_USER=unkex
      - POSTGRES_DB=unkex